workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      variables:
        # This should contain the App Store Connect API key ID
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        APP_STORE_CONNECT_KEY_ID: Encrypted(...)
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        # This is optional but useful for automated versioning
        BUILD_NUMBER: 1
    scripts:
      # Pre-install necessary dependencies
      - name: Install dependencies
        script: |
          flutter pub get
          pod repo update
      # Build the iOS app
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true